import { Roles } from "app/roles";
import { RouteInfo } from "./vertical-menu.metadata";

const { ADMIN, SUPER_ADMIN } = Roles;

//Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: "ft-home",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    hasaccess: [SUPER_ADMIN, ADMIN],
  },
  {
    path: "/admin/profile",
    title: "Profile",
    icon: "ft-user",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    hasaccess: [SUPER_ADMIN, ADMIN],
  },
  {
    path: "/admins",
    title: "Admin",
    icon: "ft-user",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    hasaccess: [SUPER_ADMIN],
  },
  {
    path: "",
    title: "Accounts",
    icon: "ft-users",
    class: "has-sub",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    hasaccess: [SUPER_ADMIN, ADMIN],
    submenu: [
      {
        path: "/organization",
        title: "Organizations",
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        submenu: [],
        hasaccess: [SUPER_ADMIN, ADMIN],
      },
      {
        path: "/sub-account",
        title: "Sub-Accounts",
        icon: "ft-arrow-right submenu-icon",
        class: "",
        badge: "",
        badgeClass: "",
        isExternalLink: false,
        submenu: [],
        hasaccess: [SUPER_ADMIN, ADMIN],
      },
    ],
  },
  {
    path: "/tags",
    title: "Tags",
    icon: "ft-map-pin",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    hasaccess: [SUPER_ADMIN, ADMIN],
  },
  {
    path: "/fans",
    title: "Fans",
    icon: "ft-heart",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    hasaccess: [SUPER_ADMIN, ADMIN],
  },
  {
    path: "/broadcasts",
    title: "Broadcasts",
    icon: "ft-speaker",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    hasaccess: [SUPER_ADMIN, ADMIN],
  },
  {
    path: "/settings",
    title: "Settings",
    icon: "ft-speaker",
    class: "",
    badge: "",
    badgeClass: "",
    isExternalLink: false,
    submenu: [],
    hasaccess: [SUPER_ADMIN, ADMIN],
  },
  // {
  //   path: '',
  //   title: 'Payments',
  //   icon: 'ft-dollar-sign',
  //   class: 'has-sub',
  //   badge: '',
  //   badgeClass: '',
  //   isExternalLink: false,
  //   submenu: [
  //     {
  //       path: '',
  //       title: 'Payment History',
  //       icon: 'ft-arrow-right submenu-icon',
  //       class: 'has-sub',
  //       badge: '',
  //       badgeClass: '',
  //       isExternalLink: false,
  //       submenu: [
  //         {
  //           path: 'payment-history/landing-page',
  //           title: 'Overview',
  //           icon: 'ft-arrow-right submenu-icon',
  //           class: '',
  //           badge: '',
  //           badgeClass: '',
  //           isExternalLink: false,
  //           submenu: [],
  //           hasaccess: [SUPER_ADMIN, ADMIN],
  //         },
  //         {
  //           path: 'payment-history/by-subscriptions',
  //           title: 'By Creators',
  //           icon: 'ft-arrow-right submenu-icon',
  //           class: '',
  //           badge: '',
  //           badgeClass: '',
  //           isExternalLink: false,
  //           submenu: [],
  //           hasaccess: [SUPER_ADMIN, ADMIN],
  //         },
  //         {
  //           path: 'payment-history/by-tp',
  //           title: 'By Rights Holders',
  //           icon: 'ft-arrow-right submenu-icon',
  //           class: '',
  //           badge: '',
  //           badgeClass: '',
  //           isExternalLink: false,
  //           submenu: [],
  //           hasaccess: [SUPER_ADMIN, ADMIN],
  //         },
  //       ],
  //       hasaccess: [SUPER_ADMIN, ADMIN],
  //     },
  //   ],
  //   hasaccess: [SUPER_ADMIN, ADMIN],
  // },

  // {
  //   path: '/contact-us',
  //   title: 'Messages',
  //   icon: 'ft-mail',
  //   class: '',
  //   badge: '',
  //   badgeClass: '',
  //   isExternalLink: false,
  //   submenu: [],
  //   hasaccess: [SUPER_ADMIN, ADMIN],
  // },
];
