import { Roles } from "./roles";

const { ADMIN, MANAGER, CREATOR, RIGHT_HOLDER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED } = Roles;

export const Permissions = Object.freeze({
  DASHBOARD: {
    LOAD: [ADMIN, MANAGER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED, CREATOR, RIGHT_HOLDER],
    VIEW_ACCOUNTS: [ADMIN, MANAGER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED],
    VIEW_CONTENT: [ADMIN, MANAGER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED],
    VIEW_REVENUE: [ADMIN, MANAGER, VIEWER],
    VIEW_ANALYTICS: [ADMIN, MANAGER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED],
  },
  ADMIN: {
    LOAD: [ADMIN],
  },
  ACCOUNTS_CREATOR: {
    LOAD: [ADMIN, MANAGER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED,],
    CRUD: [ADMIN, MANAGER, MANAGER_LIMITED],
  },
  ACCOUNTS_RIGHT_HOLDER: {
    LOAD: [ADMIN, MANAGER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED,],
    CRUD: [ADMIN, MANAGER, MANAGER_LIMITED],
  },
  ACCOUNTS_AGREEMENTS: {
    LOAD: [ADMIN, MANAGER, MANAGER_LIMITED, VIEWER, VIEWER_LIMITED,],
    CRUD: [ADMIN, MANAGER, MANAGER_LIMITED],
  },
});